### PR TITLE
Add myself

### PR DESCRIPTION
**Pull request by Zianwar**
Hello , It's a pleasure to be part of this little community of Morocan web artisans.

### CODE REVIEW

**Comment by kronik3r** [comment]
Yo, you're welcome buddy :)

**Comment by kronik3r** [comment]
@Zianwar I think that you used the wrong Indentation :) you know it's an YML file you have to use tabs rather than spaces.

**Comment by Zianwar** [comment]
@kronik3r didn't notice, I fixed it.

**Comment by alaouy** [comment]
@Zianwar happy to welcome you among us :)

**Comment by Zianwar** [comment]
@alaouy thank you :D

**Pull request merged**
